name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - "never" # Disable this workflow in my fork.
    # tags:
    #   - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build_and_publish_pypi:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build setuptools wheel twine importlib-metadata==7.2.1

    - name: Build and publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        python -m build
        twine upload dist/*

  build_and_publish_appimage:
    needs: build_and_publish_pypi
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x86_64]  # Add aarch64 when ready
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build AppImage builder
      uses: docker/build-push-action@v5
      with:
        context: .
        file: docker/appimage-builder/Dockerfile
        load: true
        tags: brade-appimage-builder:latest

    - name: Build AppImage
      run: |
        mkdir -p build
        cp build_appimage.sh build/
        chmod +x build/build_appimage.sh
        docker run --rm \
          -v ${{ github.workspace }}:/src \
          -v ${{ github.workspace }}/build:/build \
          brade-appimage-builder:latest \
          /bin/bash -c "cd /build && python3.13 -m pip install -e /src && ./build_appimage.sh"

    - name: Test AppImage
      run: |
        chmod +x build/Brade-${{ matrix.arch }}.AppImage
        ./build/Brade-${{ matrix.arch }}.AppImage --version

    - name: Upload AppImage
      uses: actions/upload-artifact@v4
      with:
        name: brade-${{ matrix.arch }}-appimage
        path: build/Brade-${{ matrix.arch }}.AppImage

    - name: Upload to Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: build/Brade-${{ matrix.arch }}.AppImage
